name = "luana-group-app"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

# D1 database binding. After you create the database (see SETUP.md),
# paste its database_id below.
[[d1_databases]]
binding = "DB"
database_name = "luana-board"
database_id = "a2008abc-ebf0-400c-929c-cf1af2cc515c"
